# Copyright (c) 2024 Nordic Semiconductor
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

manifest:
  self:
    west-commands: scripts/west-commands.yml
    path: project

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: ncs-fork
      url-base: https://github.com/Trond-F-Christiansen/

  projects:
    - name: nrf
      remote: ncs-fork
      repo-path: sdk-nrf
      revision: japan-test
      import: true
